services:
  # Unser Angular Frontend
  frontend:
    build: .
    ports:
      - "8180:80" # Erreichbar unter http://DEIN-SERVER:8180
    depends_on:
      - backend
    restart: always

  backend:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    # Wir speichern die Daten dauerhaft im Ordner pb_data
    volumes:
      - /mnt/toshiba/kochkompass:/pb_data
      - ./pb_migrations:/pb/pb_migrations
    ports:
      - "8190:8090"
    # Optional: Healthcheck
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8190/api/health"]
      interval: 50s
      timeout: 50s
      retries: 5
