server {
    listen 80;

    # 1. Alles was Frontend ist (HTML, JS, CSS)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Wichtig für Angular Routing: Wenn Datei nicht da, lade index.html
        try_files $uri $uri/ /index.html;
    }

    # 2. Alles was mit /api beginnt -> ans Backend weiterleiten
    location /api/ {
        # 'backend' ist der Name unseres Services im docker-compose
        # Wir schneiden das '/api' weg, weil json-server das nicht erwartet
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://backend:3000;
    }
}
