name: Deploy to Home Server

# Wann soll das passieren? Bei jedem Push auf main
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    # WICHTIG: Hier sagen wir, es soll auf DEINEM Server laufen
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Da der Runner auf deinem Server im Projektordner arbeitet,
      # liegen die Dateien jetzt schon da.

      - name: Docker Update
        run: |
          mkdir -p ~/docker/kochkompass
          rsync -a --exclude='.git' ./ ~/docker/kochkompass/
          cd ~/docker/kochkompass
          docker-compose up -d --build

# ssh -L 8090:localhost:8090 nisgames@192.168.178.55
